import React from "react";
import styled from "@emotion/styled";
/**
 * `<SimpleLandingPage>` ('Simple Landing Page')
 *
 *
 * ---
 * @example
 * ```tsx
 * import React from "react";
 *
 * export default function () {
 *   return (
 *     <>
 *       👇 instanciate widget like below. 👇
 *       <SimpleLandingPage/>
 *     </>
 *   )
 * }
 * ```
 * ---
 * @params {any} props - this widget does not requires props. you can pass custom dynamic props to the widget as you want (on typescript, it will raise type check issues).
 * ---
 * @preview
 * ![](https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/91ea2a22-4fbc-45e1-8561-2829d25c5020)
 * ---
 * @remarks
 * @see {@link https://grida.co/docs} for more information.
 * ---
 * Code generated by grida.co | engine 0.0.1 (Apache-2.0) | Generated code under CC0 (public domain) *This code is free to use, modify, and redistribute. (aknowledgment is not required)*
 *
 *
 * ![Made with Grida](https://bridged-service-static.s3.us-west-1.amazonaws.com/branding/logo/32.png)
 * <!-- Info: Please do not remove this comment unless intended. removing this section will break grida integrations. -->
 * <!-- grida.meta.widget_declaration | engine : 0.0.1 | source : unknown://undefined/2:11 -->
 */
export default function SimpleLandingPage() {
  return (
    <RootWrapperSimpleLandingPage>
      <Rectangle6 />
      <Rectangle7 />
      <HoldingGlassPng
        src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/3712ad34-9eca-4f80-b7cc-5d012e205ab8"
        alt="image of HoldingGlassPng"
      />
      <HamburgerMenuIcon>
        <Rectangle2 />
        <Rectangle3 />
        <Rectangle4 />
      </HamburgerMenuIcon>
      <NaturbarsLogo
        src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/872cac0d-8161-4e67-9e95-7c9766e49ce2"
        alt="image of NaturbarsLogo"
      />
      <SearchIcon>
        <Rectangle5 />
        <Ellipse1 />
        <Ellipse2 />
      </SearchIcon>
      <SimpleEasyHealthy>
        Simple,
        <br />
        Easy,
        <br />
        Healthy.
      </SimpleEasyHealthy>
    </RootWrapperSimpleLandingPage>
  );
}

const RootWrapperSimpleLandingPage = styled.div`
	min-height: 100vh;
	background-color: white;
	position: relative;
`;

const Rectangle6 = styled.div`
	width: 8px;
	height: 101px;
	background-color: black;
	position: absolute;
	left: 1459px;
	top: 485px;
	transform: rotate(-340deg);
	transform-origin: top left;
`;

const Rectangle7 = styled.div`
	width: 8px;
	height: 51px;
	background-color: black;
	position: absolute;
	left: 1459px;
	top: 494px;
	transform: rotate(-90deg);
	transform-origin: top left;
`;

const HoldingGlassPng = styled.img`
	width: 710px;
	height: 805px;
	object-fit: cover;
	position: absolute;
	left: 950px;
	top: 532px;
`;

const HamburgerMenuIcon = styled.div`
	width: 50px;
	height: 40px;
	position: absolute;
	left: 115px;
	top: 89px;
`;

const Rectangle2 = styled.div`
	width: 50px;
	height: 8px;
	background-color: black;
	border-radius: 6px;
	position: absolute;
	left: 0px;
	top: 8px;
`;

const Rectangle3 = styled.div`
	width: 35px;
	height: 8px;
	background-color: black;
	border-radius: 6px;
	position: absolute;
	left: 0px;
	top: 24px;
`;

const Rectangle4 = styled.div`
	width: 50px;
	height: 8px;
	background-color: black;
	border-radius: 6px;
	position: absolute;
	left: 0px;
	top: 40px;
`;

const NaturbarsLogo = styled.img`
	width: 413px;
	height: 67px;
	object-fit: cover;
	position: absolute;
	left: 1073px;
	top: 86px;
`;

const SearchIcon = styled.div`
	width: 41px;
	height: 42px;
	position: absolute;
	left: 2404px;
	top: 86px;
`;

const Rectangle5 = styled.div`
	width: 35px;
	height: 8px;
	background-color: black;
	border-radius: 6px;
	position: absolute;
	left: 6px;
	top: 42px;
	transform: rotate(-315deg);
	transform-origin: top left;
`;

const Ellipse1 = styled.div`
	width: 31px;
	height: 31px;
	background-color: black;
	border-radius: 31px / 31px;
	position: absolute;
	left: 10px;
	top: 0px;
`;

const Ellipse2 = styled.div`
	width: 17px;
	height: 17px;
	background-color: white;
	border-radius: 17px / 17px;
	position: absolute;
	left: 17px;
	top: 7px;
`;

const SimpleEasyHealthy = styled.span`
	color: black;
	text-overflow: ellipsis;
	font-size: 64px;
	font-family: Inter, sans-serif;
	font-weight: 600;
	text-align: right;
	position: absolute;
	left: 1519px;
	top: 453px;
`;
